import test from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs/promises';
import path from 'node:path';
import { hashDocumentText,validateExtraction } from '../lib/offer-import/validation.js';
import { resolveEvidence,inverseEvidenceResolution,processingContract,auditResolvedResult,makeResultBinding } from '../lib/offer-import/evidence-resolution.js';
import { digest } from '../lib/ai/safety-storage.js';
import { v4Fixture,wireFixture,v4Config,v4Instructions } from './fixtures/extraction-v4.js';
import { upgradeFixture } from './fixtures/extraction-upgrade.js';
import { createExtractionService } from '../lib/offer-import/extraction-service.js';
import { createArtifactStore } from '../lib/offer-import/extraction-artifacts.js';
import { createMaintenanceService } from '../lib/maintenance/backup.js';
import { validateExecutionLedgerAny } from '../lib/offer-import/execution-v4-contract.js';
import { capture,snapshotHash } from '../lib/maintenance/snapshot.js';
import { blockedConnections } from './helpers/network-guard.js';
import { extractionPages } from '../lib/offer-import/extraction-pages.js';
function fixture(text,quote=text,split=0){return {documents:[{id:'doc',format:'text',label:'架空資料',kind:'asp_material',versionLabel:'fixture',text,textHash:hashDocumentText(text),blocks:split?[{id:'before',start:0,end:split},{id:'block',start:split,end:text.length}]:[{id:'block',start:0,end:text.length}]}],wire:{schemaVersion:2,candidates:[{target:'facts',category:'feature',conversionKey:null,purpose:'fact',usage:'internal_only',text:'fictional-candidate',evidence:[{documentId:'doc',blockId:'block',quote}]}]}};}
const exact=[['surrogate','X😀Y','😀',0],['combining','Xe\u0301Y','e\u0301',0],['CRLF','A\r\nB','A\r\nB',0],['LF','A\nB','A\nB',0],['spaces tabs','A\t  B','A\t  B',0],['quotes','A“B”"C','“B”"',0],['JSON escape','A\\nB','\\n',0],['fullwidth','XＡY','Ａ',0],['nonzero block','abc XYZ','XYZ',4]];
for(const [label,text,quote,split]of exact)test(`v4 resolution ${label} exact and reversible`,()=>{const f=fixture(text,quote,split);const x=resolveEvidence(JSON.parse(JSON.stringify(f.wire)),f.documents);const e=x.candidates[0].evidence[0];assert.equal(e.start,text.indexOf(quote,split));assert.equal(e.end,e.start+quote.length);assert.equal(text.slice(e.start,e.end),quote);assert.deepEqual(inverseEvidenceResolution(x),f.wire);assert.doesNotThrow(()=>validateExtraction(x,f.documents));});
for(const [label,text,quote,code,split=0]of [
 ['zero','ABC','ABD','validation_quote_not_found'],['multiple','ABC ABC','ABC','validation_quote_ambiguous'],['overlap','aaaa','aa','validation_quote_ambiguous'],
 ['normalization','e\u0301','é','validation_quote_not_found'],['CRLF normalize','A\r\nB','A\nB','validation_quote_not_found'],['space collapse','A  B','A B','validation_quote_not_found'],['curly quote','“ABC”','"ABC"','validation_quote_not_found'],['other block','abc XYZ','abc','validation_quote_not_found',4],['cross boundary','ABCXYZ','CXY','validation_quote_not_found',3]
])test(`v4 resolution rejects ${label}`,()=>{const f=fixture(text,quote,split);assert.throws(()=>resolveEvidence(f.wire,f.documents),{code});});
for(const field of ['start','end','extra'])test(`v4 wire rejects ${field}`,()=>{const f=fixture('ABC');f.wire.candidates[0].evidence[0][field]=0;assert.throws(()=>resolveEvidence(f.wire,f.documents),{code:'validation_wire_schema'});});
test('v4 restricts document and block, never searches alternatives',()=>{const f=fixture('ABC','XYZ');const d=fixture('XYZ').documents[0];d.id='second';f.documents.push(d);assert.throws(()=>resolveEvidence(f.wire,f.documents),{code:'validation_quote_not_found'});f.wire.candidates[0].evidence[0].documentId='second';assert.doesNotThrow(()=>resolveEvidence(f.wire,f.documents));f.wire.candidates[0].evidence[0].blockId='missing';assert.throws(()=>resolveEvidence(f.wire,f.documents),{code:'validation_evidence_reference'});});
test('v4 keeps candidate and duplicate validator unchanged',()=>{const f=fixture('ABC');f.wire.candidates[0].conversionKey='bad';assert.throws(()=>resolveEvidence(f.wire,f.documents),{code:'validation_candidate_conversion_key'});f.wire.candidates[0].conversionKey=null;f.wire.candidates[0].evidence.push(structuredClone(f.wire.candidates[0].evidence[0]));assert.throws(()=>resolveEvidence(f.wire,f.documents),{code:'validation_evidence_duplicate'});});
test('v4 long fictional document resolution is deterministic without API',()=>{const text='架空😀\r\ne\u0301\t  '.repeat(2000)+'一意な架空の終端';const f=fixture(text,'一意な架空の終端',100);assert.deepEqual(resolveEvidence(f.wire,f.documents),resolveEvidence(f.wire,f.documents));assert.equal(blockedConnections.length,0);});
async function resultArtifacts(c,r){const store=createArtifactStore(c.root);return {input:(await store.read(r.inputArtifact,r.id,'input')).content,artifact:await store.read(r.validatedArtifact,r.id,'validated_extraction')};}
test('v4 fake success binds raw wire, usage, resolution and immutable internal artifact',async t=>{const c=await v4Fixture(t);const before=await fs.readFile(path.join(c.root,'offers',c.offer.id+'.json'));const r=await c.run(c.service);assert.equal(r.schemaVersion,4);assert.equal(r.profileSnapshot.schemaVersion,2);assert.equal(r.state,'succeeded');assert.equal(r.budget.reservedMilliYen,0);assert.equal(r.budget.bookedMilliYen,1);const {input,artifact}=await resultArtifacts(c,r);assert.deepEqual(auditResolvedResult(r,input,artifact),artifact.content.extraction);assert.equal(r.responseHash,digest({extraction:wireFixture(),usage:r.budget.usage}));assert.deepEqual(r.resultBinding,makeResultBinding(r,r.validatedArtifact));assert.equal(c.calls.length,1);await assert.rejects(c.service.execute(r.id,r.revision));const imported=await c.imports.get(r.savedImport.id);assert.ok(imported.candidates.every(x=>x.review.decision==='pending'&&x.review.verification==='unverified'));assert.deepEqual(await fs.readFile(path.join(c.root,'offers',c.offer.id+'.json')),before);});
for(const [label,text,quote,code]of [['zero','ABC','response-only-invalid-quote','validation_quote_not_found'],['multiple','abc abc','abc','validation_quote_ambiguous'],['overlap','aaaa','aa','validation_quote_ambiguous']])test(`v4 ${label} failure is settled, sanitized and restart terminal`,async t=>{const f=fixture(text,quote);f.wire.candidates[0].text='response-only-invalid-candidate';const c=await v4Fixture(t,{respond:()=>({extraction:f.wire,usage:{inputTokens:100,outputTokens:200}})});c.value.documents=f.documents;const r=await c.run(c.service);assert.deepEqual(r.error,{code,phase:'validation'});assert.equal(r.state,'failed_after_request');assert.equal(r.budget.state,'settled');assert.equal(r.budget.reservedMilliYen,0);for(const k of ['validatedArtifact','plannedImport','savedImport','resultBinding'])assert.equal(r[k],null);assert.equal(r.recoveryRequired,false);assert.equal(r.unknownReason,null);const snap=await capture(c.root);for(const b of Object.values(snap.files)){assert.ok(!b.toString().includes('response-only-invalid-candidate'));assert.ok(!b.toString().includes('response-only-invalid-quote'));}const v=await c.reopen().preview(r.id);assert.equal(v.token,null);const html=extractionPages(x=>String(x)).detail(v);assert.ok(html.includes(code));assert.ok(!html.includes('response-only-invalid-candidate'));await assert.rejects(c.reopen().execute(r.id,r.revision));assert.equal(c.calls.length,1);assert.equal((await createMaintenanceService(c.root).integrity()).status,'normal');});
for(const field of ['responseHash','usage','processingContract','resultBinding','inputHash','internalQuote','internalStart','artifactReference'])test(`v4 audit rejects ${field} tampering`,async t=>{const c=await v4Fixture(t);const original=await c.run(c.service);const r=structuredClone(original),{input,artifact}=await resultArtifacts(c,r);if(field==='responseHash')r.responseHash='0'.repeat(64);if(field==='usage')r.budget.usage.inputTokens++;if(field==='processingContract')r.processingContract.resolverVersion='unknown';if(field==='resultBinding')r.resultBinding.bindingHash='0'.repeat(64);if(field==='inputHash')artifact.content.inputHash='0'.repeat(64);if(field==='internalQuote')artifact.content.extraction.candidates[0].evidence[0].quote+='bad';if(field==='internalStart')artifact.content.extraction.candidates[0].evidence[0].start++;if(field==='artifactReference')r.validatedArtifact.hash='0'.repeat(64);assert.throws(()=>auditResolvedResult(r,input,artifact));});
test('v4 immutable processing, result binding and preparation approval reject mutations',async t=>{const c=await v4Fixture(t);const r=await c.service.prepare(c.value);await assert.rejects(c.store.transition(r.id,1,'approved',{approval:{at:c.now().toISOString(),hash:r.requestHash,revision:1,bindingHash:'0'.repeat(64)},budget:{...r.budget,state:'reserved',reservedMilliYen:r.estimate.maximumReservedMilliYen}}));const result=await c.run(c.service).catch(()=>null);assert.equal(result,null);const ledger=await c.store.read();for(const change of [x=>x.executions[0].revisions[0].processingContract.resolverVersion='bad',x=>x.executions[0].revisions[0].profileSnapshot.schemaVersion=1]){const bad=structuredClone(ledger);change(bad);assert.throws(()=>validateExecutionLedgerAny(bad));}});
test('v4 unknown preserves reservation and stops new work after restart',async t=>{const c=await v4Fixture(t,{respond:()=>{throw Error('response-only-provider-error');}});const r=await c.run(c.service);assert.equal(r.state,'unknown');assert.equal(r.budget.reservedMilliYen,r.estimate.maximumReservedMilliYen);assert.equal(r.recoveryRequired,true);await assert.rejects(c.reopen().execute(r.id,r.revision));const input=structuredClone(c.value);input.documents[0].label+='other';const p=await c.service.prepare(input);await assert.rejects(c.service.approve(p.id,1,{confirm:true,requestHash:p.requestHash}));assert.equal(c.calls.length,1);});
test('v4 concurrent send and durable sending crash never double-send',async t=>{const c=await v4Fixture(t);const r=await c.ready(c.service);const out=await Promise.allSettled([c.service.execute(r.id,r.revision),c.service.execute(r.id,r.revision)]);assert.equal(out.filter(x=>x.status==='fulfilled').length,1);assert.equal(c.calls.length,1);const d=await v4Fixture(t,{fault:async stage=>{if(stage==='after_sending')throw Error('fixture crash');}});const a=await d.ready(d.service);await assert.rejects(d.service.execute(a.id,a.revision));assert.equal((await d.store.get(a.id)).state,'sending');assert.equal(d.calls.length,0);await assert.rejects(d.reopen().execute(a.id,a.revision));});
test('v4 backup manifest and dry-run replay binding without restore',async t=>{const c=await v4Fixture(t);await c.run(c.service);const m=createMaintenanceService(c.root);assert.equal((await m.integrity()).status,'normal');const b=await m.create();assert.equal(b.manifest.schemaVersion,4);assert.equal(b.manifest.contracts.extractionProfileSnapshot,2);const before=snapshotHash(await capture(c.root));assert.equal((await m.dryRun(b.manifest.id)).status,'normal');assert.equal(snapshotHash(await capture(c.root)),before);});
test('v4 upgrade uses separate preparation/send approvals and preserves old source',async t=>{const c=await upgradeFixture(t);const before=await fs.readFile(path.join(c.root,'extraction-executions/ledger.json'));let calls=0;const provider={kind:'fake',async extract(){calls++;return {extraction:wireFixture(),usage:{inputTokens:100,outputTokens:200}};}};const s=createExtractionService({...c.options,provider,config:v4Config,simulationInstructions:v4Instructions,processing:processingContract()});const preview=await s.upgradePreview(c.source.id);assert.equal(calls,0);await assert.rejects(s.prepareUpgrade(c.source.id,preview.token,{confirm:false}));assert.deepEqual(await fs.readFile(path.join(c.root,'extraction-executions/ledger.json')),before);const child=await s.prepareUpgrade(c.source.id,preview.token,{confirm:true});assert.equal(child.schemaVersion,4);assert.equal(child.budget.state,'none');assert.equal(calls,0);await assert.rejects(s.execute(child.id,child.revision));const approved=await s.approve(child.id,1,{confirm:true,requestHash:child.requestHash});const result=await s.execute(child.id,approved.revision);assert.equal(result.state,'succeeded');assert.equal(calls,1);assert.deepEqual((await c.store.read()).executions[0],JSON.parse(before).executions[0]);await assert.rejects(s.upgradePreview(c.source.id));assert.equal((await createMaintenanceService(c.root).integrity()).status,'normal');});
for(const stage of ['after_response','before_validated_artifact'])test(`v4 interruption ${stage} never resends and preserves accounting`,async t=>{
  const c=await v4Fixture(t,{fault:async name=>{if(name===stage)throw Error('fictional-interruption');}});
  let r;try{r=await c.run(c.service);}catch{r=(await c.store.read()).executions[0].revisions.at(-1);}
  assert.equal(c.calls.length,1);await assert.rejects(c.reopen().execute(r.id,r.revision));
  if(stage==='after_response'){assert.equal(r.state,'sending');assert.equal(r.budget.state,'reserved');}
  else {assert.equal(r.state,'recovery_required');assert.equal(r.budget.state,'settled');assert.equal(r.resultBinding,null);assert.equal(r.validatedArtifact,null);}
});
test('v4 artifact acknowledgement failure preserves orphan and stops after restart',async t=>{
  const c=await v4Fixture(t);const original=createArtifactStore(c.root);const artifacts={...original,async create(...args){const ref=await original.create(...args);if(args[1]==='validated_extraction')throw Error('fictional-lost-ack');return ref;}};
  const r=await c.run(c.reopen({artifacts}));assert.equal(r.state,'recovery_required');assert.equal(r.resultBinding,null);assert.equal(c.calls.length,1);
  const report=await createMaintenanceService(c.root).integrity();assert.notEqual(report.status,'normal');assert.ok(report.issues.some(x=>x.code==='orphan_artifact'));
  await assert.rejects(c.reopen().execute(r.id,r.revision));assert.equal(c.calls.length,1);
});
test('v4 import save failure only permits audited local save recovery',async t=>{
  const c=await v4Fixture(t);let fail=true;const imports={...c.imports,async create(...args){if(fail){fail=false;throw Error('fictional-save-failure');}return c.imports.create(...args);}};
  const r=await c.run(c.reopen({importStore:imports}));assert.equal(r.state,'import_save_failed');assert.ok(r.resultBinding);
  const saved=await c.reopen({importStore:imports}).recover(r.id,r.revision,{confirm:true,operation:'save_only'});assert.equal(saved.state,'succeeded');assert.equal(c.calls.length,1);
});
async function upgradeV4Service(c,extra={}){return createExtractionService({...c.options,provider:{kind:'fake',async extract(){return {extraction:wireFixture(),usage:{inputTokens:100,outputTokens:200}};}},config:v4Config,simulationInstructions:v4Instructions,processing:processingContract(),...extra});}
test('v4 preparation double submit and concurrency create only one child',async t=>{
  const c=await upgradeFixture(t),s=await upgradeV4Service(c);const p=await s.upgradePreview(c.source.id);
  const results=await Promise.allSettled([s.prepareUpgrade(c.source.id,p.token,{confirm:true}),s.prepareUpgrade(c.source.id,p.token,{confirm:true})]);
  assert.ok(results.some(x=>x.status==='fulfilled'));const child=results.find(x=>x.status==='fulfilled').value;
  assert.equal((await c.store.read()).executions.length,2);assert.equal((await s.prepareUpgrade(c.source.id,p.token,{confirm:true})).id,child.id);
  await assert.rejects((await upgradeV4Service(c)).prepareUpgrade(c.source.id,p.token,{confirm:true}));
});
for(const stage of ['after_upgrade_input','before_upgrade_persist','after_upgrade_persist'])test(`v4 upgrade partial save ${stage} stops safely`,async t=>{
  const c=await upgradeFixture(t);const s=await upgradeV4Service(c,{fault:async name=>{if(name===stage)throw Error('fictional-partial-save');}}),p=await s.upgradePreview(c.source.id);
  await assert.rejects(s.prepareUpgrade(c.source.id,p.token,{confirm:true}));const ledger=await c.store.read();
  if(stage==='after_upgrade_persist'){assert.equal(ledger.executions.length,2);assert.equal((await s.prepareUpgrade(c.source.id,p.token,{confirm:true})).id,ledger.executions[1].revisions[0].id);}
  else {assert.equal(ledger.executions.length,1);assert.notEqual((await createMaintenanceService(c.root).integrity()).status,'normal');await assert.rejects(s.prepareUpgrade(c.source.id,p.token,{confirm:true}));}
});
test('v4 mixed v1/v2/v3/v4 history, legacy backups and immutable source chain',async t=>{
  const c=await upgradeFixture(t);const badProvider={kind:'fake',async extract(){return {extraction:{},usage:{inputTokens:100,outputTokens:200}};}};const oldService=createExtractionService({...c.options,provider:badProvider});const v3Service=c.reopen({provider:badProvider});const v2p=await oldService.reanalysisPreview(c.source.id);const v2=await oldService.prepareReanalysis(c.source.id,v2p.token,{confirm:true});const a=await oldService.approve(v2.id,1,{confirm:true,requestHash:v2.requestHash});const failed=await oldService.execute(v2.id,a.revision);assert.equal(failed.state,'failed_after_request');
  const v3=await c.prepareChild(v3Service,failed);const a3=await v3Service.approve(v3.id,1,{confirm:true,requestHash:v3.requestHash});const fail3=await v3Service.execute(v3.id,a3.revision);assert.equal(fail3.state,'failed_after_request');
  const m=createMaintenanceService(c.root),old=await m.create();assert.equal(old.manifest.schemaVersion,3);
  const oldLedger=await c.store.read();const s=await upgradeV4Service(c);const p=await s.upgradePreview(fail3.id);const v4=await s.prepareUpgrade(fail3.id,p.token,{confirm:true});const a4=await s.approve(v4.id,1,{confirm:true,requestHash:v4.requestHash});assert.equal((await s.execute(v4.id,a4.revision)).state,'succeeded');
  const mixed=await c.store.read();assert.deepEqual(mixed.executions.map(e=>e.revisions[0].schemaVersion),[1,2,3,4]);assert.deepEqual(mixed.executions.slice(0,3),oldLedger.executions);assert.equal((await m.integrity()).status,'normal');const legacyDry=await m.dryRun(old.manifest.id);assert.equal(legacyDry.backupValid,true);assert.equal(legacyDry.report.status,'normal');assert.ok(['normal','warning'].includes(legacyDry.status));const newer=await m.create();assert.equal(newer.manifest.schemaVersion,4);assert.equal((await m.dryRun(newer.manifest.id)).status,'normal');
});
for(const field of ['sourceHash','sourceRevision','sourceConfigurationHash','destinationConfigurationHash','operationId','kind','preparationApproval'])test(`v4 lineage rejects ${field} tampering`,async t=>{
  const c=await upgradeFixture(t),s=await upgradeV4Service(c),p=await s.upgradePreview(c.source.id);await s.prepareUpgrade(c.source.id,p.token,{confirm:true});const bad=await c.store.read(),link=bad.executions[1].revisions[0].upgrade;
  if(field==='sourceRevision')link[field]++;else if(field==='preparationApproval')link[field].kind='automatic';else if(field==='operationId')link[field]='invalid-id';else link[field]='0'.repeat(64);
  const {lineageHash,...fields}=link;link.lineageHash=digest(fields);assert.throws(()=>validateExecutionLedgerAny(bad));
});
for(const change of ['wireSchemaVersion','inverseVersion','algorithmHash','validatorHash','internalSchemaHash','wireSchemaHash'])test(`v4 unknown processing ${change} is rejected`,()=>{const f=fixture('ABC'),p=processingContract();p[change]=change==='wireSchemaVersion'?3:'0'.repeat(64);assert.throws(()=>resolveEvidence(f.wire,f.documents,p),{code:'processing_contract_invalid'});});
test('v4 zero external connection attempts',()=>assert.deepEqual(blockedConnections,[]));
test('v4 response acknowledgement uncertainty preserves durable settled record without replay',async t=>{
  const c=await v4Fixture(t);const store={...c.store,async transition(...args){const r=await c.store.transition(...args);if(args[2]==='response_received')throw Error('fictional-lost-response-ack');return r;}};
  const s=c.reopen({store});await assert.rejects(c.run(s),{code:'response_persistence_uncertain'});const r=(await c.store.read()).executions[0].revisions.at(-1);assert.equal(r.state,'response_received');assert.equal(r.budget.state,'settled');assert.equal(r.budget.reservedMilliYen,0);assert.equal(r.resultBinding,null);assert.equal(c.calls.length,1);await assert.rejects(c.reopen().execute(r.id,r.revision));const stopped=await c.reopen().recover(r.id,r.revision,{confirm:true,operation:'mark_interrupted'});assert.equal(stopped.state,'recovery_required');assert.equal(c.calls.length,1);
});
test('v4 usage unknown retains maximum reservation and never stores wire',async t=>{const c=await v4Fixture(t,{respond:()=>({extraction:wireFixture(),usage:null})});const r=await c.run(c.service);assert.equal(r.state,'unknown');assert.equal(r.unknownReason,'usage_unknown');assert.equal(r.budget.reservedMilliYen,r.estimate.maximumReservedMilliYen);assert.equal(r.responseHash,null);assert.equal(r.validatedArtifact,null);assert.equal(r.resultBinding,null);});
test('v4 import acknowledgement uncertainty requires explicit result-only finalization',async t=>{const c=await v4Fixture(t);const imports={...c.imports,async create(...args){await c.imports.create(...args);throw Error('fictional-lost-import-ack');}};const r=await c.run(c.reopen({importStore:imports}));assert.equal(r.state,'recovery_required');assert.ok(r.resultBinding);const saved=await c.reopen().recover(r.id,r.revision,{confirm:true,operation:'finalize_result'});assert.equal(saved.state,'succeeded');assert.equal(c.calls.length,1);});
for(const field of ['inputArtifact','normalizedArtifactHash','profileSnapshot','approvalBinding','boundInternalOffsets'])test(`v4 maintenance rejects ${field} despite recomputed local hashes`,async t=>{
  const c=await v4Fixture(t);const r=await c.run(c.service);const file=path.join(c.root,'extraction-executions/ledger.json'),ledger=JSON.parse(await fs.readFile(file));
  if(field==='inputArtifact'){const p=path.join(c.root,'extraction-artifacts',r.inputArtifact.id+'.json');const a=JSON.parse(await fs.readFile(p));a.content.documents[0].text+='X';a.content.documents[0].textHash=hashDocumentText(a.content.documents[0].text);a.content.documents[0].blocks.at(-1).end++;a.contentHash=digest(a.content);a.byteSize=Buffer.byteLength(JSON.stringify(a.content));await fs.writeFile(p,JSON.stringify(a));}
  else if(field==='profileSnapshot'){for(const row of ledger.executions[0].revisions)row.profileSnapshot.profile.instructions+='changed';}
  else if(field==='approvalBinding'){for(const row of ledger.executions[0].revisions)if(row.approval)row.approval.bindingHash='0'.repeat(64);}
  else {const p=path.join(c.root,'extraction-artifacts',r.validatedArtifact.id+'.json');const a=JSON.parse(await fs.readFile(p));a.content.extraction.candidates[0].evidence[0].start++;a.contentHash=digest(a.content);a.byteSize=Buffer.byteLength(JSON.stringify(a.content));await fs.writeFile(p,JSON.stringify(a));if(field==='boundInternalOffsets')for(const row of ledger.executions[0].revisions)if(row.validatedArtifact){row.validatedArtifact.hash=a.contentHash;row.validatedArtifact.bytes=a.byteSize;row.resultBinding=makeResultBinding(row,row.validatedArtifact);}}
  await fs.writeFile(file,JSON.stringify(ledger));assert.equal((await createMaintenanceService(c.root).integrity()).status,'error');
});
test('v4 upgrade field accepts only null or a valid lineage object',async t=>{
  const c=await v4Fixture(t);await c.service.prepare(c.value);const good=await c.store.read();
  for(const value of [false,0,'',[],undefined]){const bad=structuredClone(good);bad.executions[0].revisions[0].upgrade=value;assert.throws(()=>validateExecutionLedgerAny(bad));}
});
test('legacy v3 cannot adopt snapshot v2 without a v4 execution contract',async t=>{
  const {validateExecutionAny}=await import('../lib/offer-import/execution-v3-contract.js');
  const c=await upgradeFixture(t);const child=await c.prepareChild();const changed=structuredClone(child);
  changed.profileSnapshot.schemaVersion=2;changed.profileSnapshot.profile.processingContract=processingContract();
  assert.throws(()=>validateExecutionAny(changed),{code:'historical_profile_invalid'});
});
test('legacy execution cannot acquire the wire v2 profile by configuration lookup',async()=>{
  const {resolveAuditProfile}=await import('../lib/ai/extraction-profile-registry.js');const {extractionProfile,profileConfiguration}=await import('../lib/ai/extraction-profile.js');
  const config=profileConfiguration();const legacy={schemaVersion:1,provider:'openai',model:extractionProfile.model,configuration:{...config,hash:digest(config)}};
  assert.throws(()=>resolveAuditProfile(legacy),{code:'historical_profile_invalid'});
});
