import test from 'node:test';
import assert from 'node:assert/strict';
import { createApp } from '../server.js';
import { v5Fixture,v5Config,v5Instructions } from './fixtures/extraction-v5.js';
import { processingContract } from '../lib/offer-import/evidence-resolution-v2.js';
import { upgradeFixture } from './fixtures/extraction-upgrade.js';
import { capture,snapshotHash } from '../lib/maintenance/snapshot.js';
async function appFixture(t){const c=await upgradeFixture(t);const app=createApp({dataDirectory:c.root,generationOptions:{now:c.now},extractionOptions:{provider:{kind:'fake',async extract(){throw Error('fictional-no-send');}},config:v5Config,simulationInstructions:v5Instructions,processing:processingContract(),now:c.now}});await new Promise((resolve,reject)=>{app.once('error',reject);app.listen(0,'127.0.0.1',resolve);});t.after(()=>new Promise(resolve=>app.close(resolve)));return {...c,base:`http://127.0.0.1:${app.address().port}`};}
test('v5 HTTP dedicated preparation displays no model offsets, stays unapproved and unreserved',async t=>{const c=await appFixture(t),before=snapshotHash(await capture(c.root));const detail=await fetch(c.base+'/offer-extractions/'+c.source.id);assert.match(await detail.text(),/現在設定で再抽出する準備を確認する/);const preview=await fetch(c.base+'/offer-extractions/'+c.source.id+'/configuration-upgrade');const html=await preview.text();assert.equal(preview.status,200);assert.ok(html.includes('現在設定での再抽出・準備確認'));assert.ok(html.includes('name="token"'));assert.equal(snapshotHash(await capture(c.root)),before);const token=html.match(/name="token" value="([^"]+)"/)[1];const response=await fetch(c.base+'/offer-extractions/'+c.source.id+'/configuration-upgrade/prepare',{method:'POST',headers:{Origin:c.base},body:new URLSearchParams({token,confirm:'yes'}),redirect:'manual'});assert.equal(response.status,303);const id=response.headers.get('location').split('/').at(-1),r=await c.store.get(id);assert.equal(r.schemaVersion,5);assert.equal(r.profileSnapshot.schemaVersion,3);assert.equal(r.budget.reservedMilliYen,0);const childPage=await fetch(c.base+response.headers.get('location'));assert.match(await childPage.text(),/execution v5/);});
test('v5 HTTP unchecked preparation never creates child',async t=>{const c=await appFixture(t);const html=await (await fetch(c.base+'/offer-extractions/'+c.source.id+'/configuration-upgrade')).text();const token=html.match(/name="token" value="([^"]+)"/)[1];const before=snapshotHash(await capture(c.root));const response=await fetch(c.base+'/offer-extractions/'+c.source.id+'/configuration-upgrade/prepare',{method:'POST',headers:{Origin:c.base},body:new URLSearchParams({token}),redirect:'manual'});assert.equal(response.status,400);assert.equal(snapshotHash(await capture(c.root)),before);});
test('v5 HTTP invalid cross-origin preparation refuses before mutation',async t=>{const c=await appFixture(t);const before=snapshotHash(await capture(c.root));const response=await fetch(c.base+'/offer-extractions/'+c.source.id+'/configuration-upgrade/prepare',{method:'POST',headers:{Origin:'http://fictional-invalid.local'},body:new URLSearchParams({token:'invalid',confirm:'yes'})});assert.equal(response.status,403);assert.equal(snapshotHash(await capture(c.root)),before);});
