// Static diagnostic vocabulary only. Never include payload, paths, quotes, or raw exceptions.
export const validationReasons = Object.freeze({
  validation_failed: '抽出結果の検証に失敗しました。詳細理由の記録はありません。過去の失敗理由は推測しません。',
  validation_response: 'Provider応答の内部形式が一致しません。',
  validation_input: '固定入力資料の形式・hash・block構成を検証できません。',
  validation_schema: '抽出結果が既存schemaの形式・必須項目・値の制約を満たしていません。',
  validation_candidate: '候補の対象・分類・用途・成果地点の対応が既存契約と一致しません。',
  validation_candidate_conversion_key: '成果地点グループの必須・null条件に一致しません。',
  validation_candidate_target_category: '対象と分類の対応に一致しません。',
  validation_candidate_reward: '報酬分類の対象・内部専用条件に一致しません。',
  validation_candidate_conversion_purpose: '成果条件の対象に必要な用途と一致しません。',
  validation_candidate_conversion_target: '成果条件用途を許可しない対象です。',
  validation_candidate_prohibited: '禁止事項の用途・制約専用条件に一致しません。',
  validation_candidate_marketing_target: '訴求目標用途を許可しない対象です。',
  validation_candidate_restriction_target: '禁止用途を許可しない対象です。',
  validation_candidate_unmapped: '未分類の対象・用途・内部専用条件に一致しません。',
  validation_candidate_prohibition_target: '禁止分類を許可しない対象です。',
  validation_evidence_reference: '根拠のdocument IDまたはblock IDが固定資料に存在しません。',
  validation_evidence_range: '根拠の位置範囲がblockの範囲内に収まっていない、または開始・終了の順序が不正です。',
  validation_wire_schema: '位置なしwire schema v2/v3の形式に一致しません。',
  validation_quote_not_found: '指定block内にquoteの完全一致がありません。本文や位置の補正は行いません。',
  validation_quote_ambiguous: '指定block内にquoteが複数出現します。重なる出現も含め、一意に決定できません。',
  validation_resolution_roundtrip: '位置解決と逆変換の往復一致を検証できません。',
  validation_quote: '根拠のquoteが指定位置の原文と完全一致しません。',
  validation_quote_found_elsewhere_in_block: '根拠のquoteは指定位置と一致せず、同じblockの別開始位置に完全一致する原文が存在します。観測分類であり原因断定ではありません。',
  validation_quote_length_mismatch: '根拠のquoteと指定範囲のUTF-16長が異なり、原文と完全一致しません。観測分類であり原因断定ではありません。',
  validation_quote_same_length_mismatch: '根拠のquoteと指定範囲のUTF-16長は同じですが、原文と完全一致しません。観測分類であり原因断定ではありません。',
  validation_evidence_duplicate: '同じ候補内で同一の根拠が重複しています。',
  validation_secret: '秘密情報または許可しない管理画面形式の安全検査で拒否しました。',
});
export const validationReasonCode = code => Object.hasOwn(validationReasons, code) ? code : 'validation_failed';
